// <auto-generated />
using System;
using KakeiboForMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KakeiboForMVC.Migrations
{
    [DbContext(typeof(KakeiboForMVCContext))]
    [Migration("20250622064706_AddHimoku")]
    partial class AddHimoku
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KakeiboForMVC.Models.KAKEIBO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("HIDUKE")
                        .HasColumnType("datetime2");

                    b.Property<int>("HIMOKU_ID")
                        .HasColumnType("int");

                    b.Property<string>("MEISAI")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("NYUKINGAKU")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("SHUKINGAKU")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ID");

                    b.ToTable("KAKEIBO");
                });
#pragma warning restore 612, 618
        }
    }
}
